name: CI

on:
  push:
    branches:
    - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies and deploy to main
      run: |
        echo yarn install
        echo npm run deploy
